---
title: "Unit 4 - Surviving the Titanic"
subtitle: "by Ellen Savoye"
output: html_notebook
---

The 'Titanic' data set on Cran provides information on the fate of passengers on
the fatal maiden voyage of the ocean liner "Titanic", summarized according
to economic status (class), sex, age and survival. 

This data is being used to investigate whether or not someone would have a chance of surviving the sinking of the Titanic. To start the investigation, I have some exploratory visualization created with ggplot().  

```{r}
# titanic is avaliable in your workspace
# 1 - Check the structure of titanic
str(titanic)

# 2 - Use ggplot() for the first instruction
ggplot(titanic, aes(x = Pclass, fill = Sex)) +
  geom_bar(position = "dodge")

# 3 - Plot 2, add facet_grid() layer
ggplot(titanic, aes(x = Pclass, fill = Sex)) +
  geom_bar(position = "dodge") +
  facet_grid(. ~ Survived)

# 4 - Define an object for position jitterdodge, to use below
posn.jd <- position_jitterdodge(0.5, 0, 0.6)

# 5 - Plot 3, but use the position object from instruction 4
ggplot(titanic, aes(x = Pclass, y = Age, col = Sex)) +
  geom_point(size = 3, alpha =0.5, position = posn.jd) +
  facet_grid(. ~ Survived)


```

Add a new chunk by clicking the *Insert Chunk* button on the toolbar or by pressing *Ctrl+Alt+I*.

When you save the notebook, an HTML file containing the code and output will be saved alongside it (click the *Preview* button or press *Ctrl+Shift+K* to preview the HTML file).

The preview shows you a rendered HTML copy of the contents of the editor. Consequently, unlike *Knit*, *Preview* does not run any R code chunks. Instead, the output of the chunk when it was last run in the editor is displayed.
